# Generated by Django 3.1.3 on 2021-01-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='illness',
            name='more',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='illness',
            name='symptoms',
            field=models.TextField(),
        ),
    ]
