# Generated by Django 3.1.3 on 2021-01-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210115_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='more',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
